databases:
  - name: mysql-test
    databaseName: mysql_test_ifi4
    user: mysql_test_ifi4_user

services:
  - type: web
    name: final-bolo
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysql_test_ifi4
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false